# env and task
env:
  name: HalfCheetah-v4
  task: ""
  exp_name: ibc_${replay_buffer.dataset}
  n_samples_stats: 1000
  seed: 0
  backend: gymnasium

# logger
logger:
  backend: wandb
  project_name: torchrl_example_ibc
  exp_name: ibc_${replay_buffer.dataset}
  group_name: null
  eval_iter: 10_000
  eval_steps: 5000
  mode: online
  eval_envs: 1
  video: True

# replay buffer
replay_buffer:
  backend: d4rl
  dataset: halfcheetah-expert-v2
  batch_size: 512

# optimization
optim:
  device: cpu
  lr: 5e-4
  weight_decay: 0.0
  gradient_steps: 100_000
  lr_decay: 0.99

# network
model:
  num_cells: 512
  depth: 8
  activation: relu

  # stochastic optimizer hyperparameters
  optimizer:
    type: mcmc # dfo, mcmc, autoregressive_dfo

compile:
  compile: False
  compile_mode:
  cudagraphs: False
